# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jord I Hovedet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jord I Hovedet

  target 'Jord I HovedetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Jord I HovedetUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Firebase/Core'
pod 'FirebaseFirestore'
pod 'FirebaseAuth'


end
